name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy'
        required: false
        default: 'latest'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CONTAINERAPPS_ENVIRONMENT: ${{ secrets.AZURE_CONTAINERAPPS_ENVIRONMENT }}
      ACR_NAME: ${{ secrets.ACR_NAME }}
      APP_NAME: ${{ secrets.APP_NAME }}
      LOCATION: ${{ secrets.AZURE_LOCATION || 'eastus' }}
      IMAGE_REPO: agent-factory
      IMAGE_TAG: ${{ github.event.inputs.image_tag || 'latest' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI - install containerapp extension
        run: az extension add --name containerapp --upgrade

      - name: Build and push image to ACR
        run: |
          az acr login --name "$ACR_NAME"
          IMAGE="${ACR_NAME}.azurecr.io/${IMAGE_REPO}:${IMAGE_TAG}"
          echo "Building $IMAGE"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy infrastructure (Bicep)
        run: |
          az account set --subscription "$AZURE_SUBSCRIPTION_ID"
          az group create --name "$AZURE_RESOURCE_GROUP" --location "$LOCATION"
          az deployment group create \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --template-file infra/azure/main.bicep \
            --parameters \
              envName="$AZURE_CONTAINERAPPS_ENVIRONMENT" \
              location="$LOCATION" \
              acrName="$ACR_NAME" \
              appName="$APP_NAME" \
              imageRepo="$IMAGE_REPO" \
              imageTag="$IMAGE_TAG"

      - name: Output Container App URL
        run: |
          FQDN=$(az containerapp show -n "$APP_NAME" -g "$AZURE_RESOURCE_GROUP" --query properties.configuration.ingress.fqdn -o tsv)
          echo "App URL: https://$FQDN"
